# Generated by Django 3.1.2 on 2020-11-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userID', default='', on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.IntegerField(blank=True, db_column='clientID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationid',
            field=models.IntegerField(blank=True, db_column='locationID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancedata',
            name='model_number',
            field=models.OneToOneField(blank=True, db_column='model number', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.IntegerField(blank=True, db_column='model number', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceid',
            field=models.IntegerField(blank=True, db_column='serviceID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testsequence',
            name='sequenceid',
            field=models.IntegerField(blank=True, db_column='sequenceID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teststandard',
            name='standardid',
            field=models.IntegerField(blank=True, db_column='standardID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(blank=True, db_column='userID', primary_key=True, serialize=False),
        ),
    ]
